config-version: 1.0 # Do not change this value, it is used internally by the plugin to determine if the config is up to date.

checks:
  entities:
    enabled: true
    max-occluding-count: 3
    raycast-radius: 48
    always-show-radius: 16 # radius to always show entities
    recheck-interval: 50 # ticks between forced rechecks for visible entities
    engine-mode: 1 # 1 = straight-line; 2 = predictive and straight-line
  tile-entities:
    enabled: true
    max-occluding-count: 3
    raycast-radius: 48
    always-show-radius: 16
    recheck-interval: 0 # seconds between forced rechecks for visible tile entities. If set to 0, they will never be rechecked.
    engine-mode: 1 # 1 = straight-line; 2 = predictive and straight-line
  players:
    enabled: false
    only-cull-sneaking: false
    max-occluding-count: 3
    raycast-radius: 48
    always-show-radius: 16
    recheck-interval: 50 # ticks between forced rechecks for visible players
    engine-mode: 1 # 1 = straight-line; 2 = predictive and straight-line
snapshots:
  chunk-refresh-interval: 60 # seconds between chunk snapshot refresh, won't change without restart
debug:
  log-level: 1 # Scale from 0-10, where larger numbers mean more verbose logging and 0 disables logging
  particles: false # enable debug particles
